# Generated by Django 5.2 on 2025-12-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('patient_id', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
