# Generated by Django 5.2 on 2026-01-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvital',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='patientvital',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='record_hash',
            field=models.CharField(default='', max_length=66),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='spo2',
            field=models.IntegerField(),
        ),
    ]
